### ISSUE TITLE
Debug cannot have "," in task description 

### ISSUE THREAD

**Issue by yiwen101** [AY2324S1-CS2103T-T11-3/tp#126]

**Comment by yiwen101** [comment]
Defer after mileStone 1.3b

**Comment by HollaG** [comment]
I will find a better way to implement this in future
Unlikely to be completed before Thursday

**Comment by yiwen101** [comment]
That is the way
As it is a "bug" rather than new feature, safely do this after the feature freeze :)

**Comment by HollaG** [comment]
Fixed in #142
