### ISSUE TITLE
Highlighted student

### ISSUE THREAD

**Issue by elaineshijie** [AY2324S1-CS2103T-T11-3/tp#173]
Click on a student and edit the student. You will see that the selected student changed
>:C

**Comment by yiwen101** [comment]
Emm, I think that is an intended feature, to always show the newly added/edited entry

**Comment by elaineshijie** [comment]
> Emm, I think that is an intended feature, to always show the newly added/edited entry

Hmm I don't think it is the intended feature, selected student is not the newly edited entry but the one before the previously selected student

<img width="912" alt="Screenshot 2023-11-04 at 8 58 26 PM" src="https://github.com/AY2324S1-CS2103T-T11-3/tp/assets/122242919/e6ee9fc6-4f83-43b1-9215-262416ae747e">

**Comment by elaineshijie** [comment]
Minor issue:
<img width="918" alt="Screenshot 2023-11-04 at 9 01 03 PM" src="https://github.com/AY2324S1-CS2103T-T11-3/tp/assets/122242919/51517a65-10ca-44aa-850a-0cc87ff30505">
<img width="909" alt="Screenshot 2023-11-04 at 9 01 13 PM" src="https://github.com/AY2324S1-CS2103T-T11-3/tp/assets/122242919/d20296d5-3145-432e-a040-93b0005b4e16">

**Comment by yiwen101** [comment]
I just see this issue; could you elaborate on what is the issue?

**Comment by elaineshijie** [comment]
@yiwen101 
After **clicking** on the third student (left panel) and using the command: "edit 3 -subject biology"
After successfully editing the student, the selected student on the left panel jumps to the index before it as shown below  (the show student panel is correct - showing the edited student):

Before editing student at index 3:
<img width="916" alt="Screenshot 2023-11-09 at 11 24 43 AM" src="https://github.com/AY2324S1-CS2103T-T11-3/tp/assets/122242919/52e64595-1f99-4679-8b6a-dcb1b8e3ac0e">
After editing student at index 3:
<img width="909" alt="Screenshot 2023-11-09 at 11 24 55 AM" src="https://github.com/AY2324S1-CS2103T-T11-3/tp/assets/122242919/219908ec-ebf1-4a4b-8bd8-d899a1fea124">
Third student shown with edited field but left panel shows selected student to be student at index 2.


Can choose to close this issue if not important/ not fixing/ not allowed to fix.

**Comment by yiwen101** [comment]
Emm, I do not know how to fix.
Looks like a GUI issue.
Probably close for now?
