### ISSUE TITLE
[PE-D][Tester C] Requires opening of team's online user guide to access help

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-3/tp#186]
![Screenshot 2023-11-03 at 4.11.46 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/3de1f045-6c83-49e7-8760-2343bfddd234.png)

After keying in 'help' to get some help, I need to copy the url and open the user guide on a browser. I think it would be easier for the user if some commands and example could be given within the application instead.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: vivienherq/ped#1

**Comment by pzl111** [comment]
Will add more descriptive help in command box
