### ISSUE TITLE
[PE-D][Tester B] Edit a student's name have unexpected output

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T11-3/tp#194]
Command: edit 1 -name Alex
According to your group's UG, for the above command it is supposed to change only the student's name. However when I tried it out, it also clears the email and address of the student.

Before:

![before.png](https://raw.githubusercontent.com/songgthu/ped/main/files/f0dee885-cc23-420f-92c0-118894148e1d.png)

After:

![after.png](https://raw.githubusercontent.com/songgthu/ped/main/files/24dbc9e4-b5da-4d35-b0e5-e5787007487c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: songgthu/ped#2

**Comment by HollaG** [comment]
Fixed in #180
