### ISSUE TITLE
[PE-D][Tester D] Formatting of example delete command in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-3/tp#217]
![image.png](https://raw.githubusercontent.com/xyT-T/ped/main/files/265a75f6-6242-48b7-b279-3c07b16e8c9a.png)
The formatting is a bit messy here.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: xyT-T/ped#11

**Comment by pzl111** [comment]
Fixed in #222
