### ISSUE TITLE
Modify picture of UI parts

### ISSUE THREAD

**Issue by yiwen101** [AY2324S1-CS2103T-T11-3/tp#259]
- [x] Change command line to command box.
- [ ] Add illustration for task list, schedule list, student list.
- [ ] Standardize the phrases we use in the UG.
- [ ] Add them to glossary and add footnotes/links

**Comment by elaineshijie** [comment]
First point: Made the necessary changes in the Ui picture
Second point: did not add the illustrations as there are pictures attached under list command
Third point: Working on it after everything is done
Fourth point: It is already under basic usage (instead of glossary)
