### ISSUE TITLE
Delete command accepts special characters

### ISSUE THREAD

**Issue by HollaG** [AY2324S1-CS2103T-T11-3/tp#282]
Delete command accepts special characters if it is preceded by a valid integer. Is this intended?

`delete 3!2` --> deletes the 3rd item
`delete !2` --> fails as expected

**Comment by richiehx** [comment]
Seems to have been a change in one of the recent PRs. Might need to figure out what caused this.

**Comment by yiwen101** [comment]
Updated UG note to specify the rule of how extra parameter and flags could be ignored, and add disclaimer against deliberate abuse
